FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. service.proto

# Comando para rodar o gRPC (em background) e o FastAPI juntos
CMD python service_grpc.py & uvicorn app:app --host 0.0.0.0 --port 5000