# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\nscheduling\"a\n\x12\x41ppointmentRequest\x12\x12\n\npatient_id\x18\x01 \x01(\t\x12\x11\n\tdoctor_id\x18\x02 \x01(\t\x12\x11\n\tspecialty\x18\x03 \x01(\t\x12\x11\n\tdate_time\x18\x04 \x01(\t\"N\n\x13\x41ppointmentResponse\x12\x16\n\x0e\x61ppointment_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\'\n\rStatusRequest\x12\x16\n\x0e\x61ppointment_id\x18\x01 \x01(\t\"8\n\x0eStatusResponse\x12\x16\n\x0e\x61ppointment_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"A\n\x13UpdateStatusRequest\x12\x16\n\x0e\x61ppointment_id\x18\x01 \x01(\t\x12\x12\n\nnew_status\x18\x02 \x01(\t2\x8a\x02\n\x11SchedulingService\x12T\n\x11\x43reateAppointment\x12\x1e.scheduling.AppointmentRequest\x1a\x1f.scheduling.AppointmentResponse\x12M\n\x14GetAppointmentStatus\x12\x19.scheduling.StatusRequest\x1a\x1a.scheduling.StatusResponse\x12P\n\x0cUpdateStatus\x12\x1f.scheduling.UpdateStatusRequest\x1a\x1f.scheduling.AppointmentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPOINTMENTREQUEST']._serialized_start=29
  _globals['_APPOINTMENTREQUEST']._serialized_end=126
  _globals['_APPOINTMENTRESPONSE']._serialized_start=128
  _globals['_APPOINTMENTRESPONSE']._serialized_end=206
  _globals['_STATUSREQUEST']._serialized_start=208
  _globals['_STATUSREQUEST']._serialized_end=247
  _globals['_STATUSRESPONSE']._serialized_start=249
  _globals['_STATUSRESPONSE']._serialized_end=305
  _globals['_UPDATESTATUSREQUEST']._serialized_start=307
  _globals['_UPDATESTATUSREQUEST']._serialized_end=372
  _globals['_SCHEDULINGSERVICE']._serialized_start=375
  _globals['_SCHEDULINGSERVICE']._serialized_end=641
# @@protoc_insertion_point(module_scope)
