# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SchedulingServiceStub(object):
    """Aqui definimos o "Contrato" do seu serviço. 
    É a lista de coisas que o seu serviço de agendamento sabe fazer.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAppointment = channel.unary_unary(
                '/scheduling.SchedulingService/CreateAppointment',
                request_serializer=service__pb2.AppointmentRequest.SerializeToString,
                response_deserializer=service__pb2.AppointmentResponse.FromString,
                _registered_method=True)
        self.GetAppointmentStatus = channel.unary_unary(
                '/scheduling.SchedulingService/GetAppointmentStatus',
                request_serializer=service__pb2.StatusRequest.SerializeToString,
                response_deserializer=service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.UpdateStatus = channel.unary_unary(
                '/scheduling.SchedulingService/UpdateStatus',
                request_serializer=service__pb2.UpdateStatusRequest.SerializeToString,
                response_deserializer=service__pb2.AppointmentResponse.FromString,
                _registered_method=True)


class SchedulingServiceServicer(object):
    """Aqui definimos o "Contrato" do seu serviço. 
    É a lista de coisas que o seu serviço de agendamento sabe fazer.
    """

    def CreateAppointment(self, request, context):
        """1. Criar um agendamento [cite: 53, 54]
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAppointmentStatus(self, request, context):
        """2. Consultar o status de uma consulta [cite: 56, 57]
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStatus(self, request, context):
        """3. Atualizar status (será usado quando a validação der o OK) [cite: 58, 61]
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAppointment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAppointment,
                    request_deserializer=service__pb2.AppointmentRequest.FromString,
                    response_serializer=service__pb2.AppointmentResponse.SerializeToString,
            ),
            'GetAppointmentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAppointmentStatus,
                    request_deserializer=service__pb2.StatusRequest.FromString,
                    response_serializer=service__pb2.StatusResponse.SerializeToString,
            ),
            'UpdateStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStatus,
                    request_deserializer=service__pb2.UpdateStatusRequest.FromString,
                    response_serializer=service__pb2.AppointmentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scheduling.SchedulingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scheduling.SchedulingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SchedulingService(object):
    """Aqui definimos o "Contrato" do seu serviço. 
    É a lista de coisas que o seu serviço de agendamento sabe fazer.
    """

    @staticmethod
    def CreateAppointment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduling.SchedulingService/CreateAppointment',
            service__pb2.AppointmentRequest.SerializeToString,
            service__pb2.AppointmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAppointmentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduling.SchedulingService/GetAppointmentStatus',
            service__pb2.StatusRequest.SerializeToString,
            service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduling.SchedulingService/UpdateStatus',
            service__pb2.UpdateStatusRequest.SerializeToString,
            service__pb2.AppointmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
